# Generated by Django 3.1.5 on 2021-08-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sublocation',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
