# Generated by Django 3.2.6 on 2021-08-09 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subdomain', models.CharField(max_length=255)),
                ('created_on', models.DateField(auto_now=True)),
                ('postal_code', models.CharField(max_length=255, null=True)),
                ('telephone', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('pin_number', models.CharField(max_length=255, null=True)),
                ('vat_number', models.CharField(max_length=255, null=True)),
                ('payroll_date', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantAwareModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('vehicle_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=255)),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('registration', models.CharField(max_length=255, unique=True)),
                ('make', models.CharField(blank=True, max_length=255)),
                ('vehicle_model', models.CharField(blank=True, max_length=255)),
                ('body_color', models.CharField(blank=True, max_length=128)),
                ('body_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.vehicletype')),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
    ]
