# Generated by Django 3.2.6 on 2021-08-09 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('fuel_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('fuel_type', models.CharField(blank=True, max_length=255)),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('stock_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('examples', models.CharField(blank=True, max_length=255)),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('tank_id', models.AutoField(primary_key=True, serialize=False)),
                ('tank_code', models.CharField(blank=True, max_length=255)),
                ('tank_capacity', models.DecimalField(decimal_places=2, max_digits=100)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.fueltype')),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('stock_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(blank=True, max_length=20)),
                ('item_description', models.CharField(blank=True, max_length=255)),
                ('item_part_number', models.CharField(blank=True, max_length=255)),
                ('item_location', models.CharField(blank=True, max_length=50)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stockcategory')),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='FuelPump',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('fuel_pump_id', models.AutoField(primary_key=True, serialize=False)),
                ('fuel_pump_code', models.CharField(blank=True, max_length=20)),
                ('fuel_pump_tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.tank')),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
    ]
