# Generated by Django 3.1.5 on 2021-08-20 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_auto_20210812_1200'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0007_customertransaction_journalentry_makepayment_receivepayment_suppliertransaction'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockArticleReceipt',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('stock_article_receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_no', models.CharField(max_length=128, unique=True)),
                ('type', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reference_no', models.CharField(blank=True, max_length=255, null=True)),
                ('part_number', models.CharField(max_length=128)),
                ('quantity_received', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=100)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=100)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('posted_date', models.DateField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stockitem')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stockcategory')),
                ('posted_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.tenantsupplier')),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='StockArticleIssue',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('stock_article_issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_no', models.CharField(max_length=128, unique=True)),
                ('type', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reference_no', models.CharField(blank=True, max_length=255, null=True)),
                ('part_number', models.CharField(max_length=128)),
                ('quantity_received', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=100)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=100)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('posted_date', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.tenantcustomer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stockitem')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stockcategory')),
                ('posted_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='StockArticleAdjustment',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('stock_article_adjustment_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_no', models.CharField(max_length=128, unique=True)),
                ('type', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reference_no', models.CharField(blank=True, max_length=255, null=True)),
                ('part_number', models.CharField(max_length=128)),
                ('required_quantity', models.IntegerField()),
                ('current_quantity', models.IntegerField()),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('posted_date', models.DateField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stockitem')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stockcategory')),
                ('posted_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
    ]
