# Generated by Django 3.2.6 on 2021-09-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stockarticleadjustment_stockarticleissue_stockarticlereceipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='item_location',
        ),
    ]
