# Generated by Django 3.2.6 on 2021-09-21 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_stockitem_item_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelpump',
            name='fuel_pump_tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.tank', unique=True),
        ),
    ]
