# Generated by Django 3.2.6 on 2021-09-21 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_fuelpump_fuel_pump_tank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelpump',
            name='fuel_pump_tank',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.tank'),
        ),
    ]
