# Generated by Django 3.2.6 on 2021-09-21 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_branch'),
        ('stock', '0005_alter_fuelpump_fuel_pump_tank'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelpump',
            name='fuel_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.branch'),
        ),
    ]
