# Generated by Django 3.2.6 on 2021-09-21 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_alter_tenantawaremodel_id'),
        ('stock', '0006_fuelpump_fuel_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelReadings',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('fuel_readings_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('morning_tank_dipping', models.DecimalField(decimal_places=2, max_digits=100)),
                ('morning_pump_reading', models.DecimalField(decimal_places=2, max_digits=100)),
                ('evening_tank_dipping', models.DecimalField(decimal_places=2, max_digits=100)),
                ('evening_pump_reading', models.DecimalField(decimal_places=2, max_digits=100)),
                ('fuel_pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.fuelpump')),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
    ]
