# Generated by Django 3.2.6 on 2021-08-09 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_category', models.CharField(blank=True, max_length=255)),
                ('department_description', models.CharField(blank=True, max_length=255)),
                ('department_narration', models.CharField(blank=True, max_length=255)),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('designation_id', models.AutoField(primary_key=True, serialize=False)),
                ('designation_code', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_code', models.CharField(blank=True, max_length=255)),
                ('employee_first_name', models.CharField(blank=True, max_length=255)),
                ('employee_last_name', models.CharField(blank=True, max_length=255)),
                ('employee_department', models.CharField(blank=True, max_length=255)),
                ('employee_id_number', models.CharField(blank=True, max_length=255)),
                ('employee_kra_pin', models.CharField(blank=True, max_length=255)),
                ('employee_sex', models.CharField(blank=True, max_length=255)),
                ('employee_address', models.CharField(blank=True, max_length=255)),
                ('employee_account_number', models.CharField(blank=True, max_length=255)),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='NhifBand',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('nhif_band_id', models.AutoField(primary_key=True, serialize=False)),
                ('nhif_band_description', models.CharField(blank=True, max_length=255)),
                ('nhif_band_lower_range', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paye_band_upper_range', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paye_band_amount', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='PayeBand',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('paye_band_id', models.AutoField(primary_key=True, serialize=False)),
                ('paye_band_tax', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paye_band_description', models.CharField(blank=True, max_length=255)),
                ('paye_band_lower_range', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paye_band_upper_range', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paye_band_amount', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='PayrollCode',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('payroll_code_id', models.AutoField(primary_key=True, serialize=False)),
                ('payroll_code', models.CharField(blank=True, max_length=20)),
                ('payroll_description', models.CharField(blank=True, max_length=255)),
                ('payroll_usage', models.CharField(blank=True, max_length=255)),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='TransportPayrollRate',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('transport_pay_roll_rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('single_bundle', models.DecimalField(decimal_places=2, max_digits=20)),
                ('double_bundle', models.DecimalField(decimal_places=2, max_digits=20)),
                ('weighing_clerk_bundle', models.DecimalField(decimal_places=2, max_digits=20)),
                ('field_clerk_bundle', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cameco_operator', models.DecimalField(decimal_places=2, max_digits=20)),
                ('bell_operator', models.DecimalField(decimal_places=2, max_digits=20)),
                ('winch_operator', models.DecimalField(decimal_places=2, max_digits=20)),
                ('loader', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_date', models.DateField(auto_now=True)),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
    ]
