# Generated by Django 3.1.5 on 2021-08-13 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_designation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.designation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.department'),
        ),
    ]
