# Generated by Django 3.1.5 on 2021-08-13 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20210813_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nhifband',
            old_name='paye_band_amount',
            new_name='nhif_band_amount',
        ),
        migrations.RenameField(
            model_name='nhifband',
            old_name='paye_band_upper_range',
            new_name='nhif_band_upper_range',
        ),
    ]
