# Generated by Django 3.1.5 on 2021-08-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_sex',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=255),
        ),
    ]
