# Generated by Django 3.1.5 on 2021-08-18 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_auto_20210812_1200'),
        ('hr', '0005_auto_20210814_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportpayrollrate',
            old_name='loader',
            new_name='loader_rate',
        ),
        migrations.CreateModel(
            name='Loader',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('loaders_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_registered', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
    ]
