# Generated by Django 3.2.6 on 2021-08-09 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsGroupingListing',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('accounts_grouping_listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('classification', models.CharField(blank=True, max_length=255)),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='AccountsHeadingsListing',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('accounts_heading_listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='AssetsGroupingListing',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('assets_grouping_listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('depreciation', models.DecimalField(decimal_places=5, max_digits=20)),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='AssetsRegisterListing',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('assets_register_listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('acc_no', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('group', models.CharField(blank=True, max_length=255)),
                ('value', models.DecimalField(decimal_places=5, max_digits=20)),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='GeneralLedgerListing',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('general_ledger_listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('acc_no', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=200)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=200)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=200)),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='TenantCustomer',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('tenant_customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_postal_code', models.CharField(max_length=255, null=True)),
                ('customer_telephone', models.CharField(max_length=255, null=True)),
                ('customer_email', models.EmailField(max_length=255, null=True)),
                ('customer_pin_number', models.CharField(max_length=255, null=True)),
                ('customer_vat_number', models.CharField(max_length=255, null=True)),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='TenantSupplier',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('supplier_customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('supplier_postal_code', models.CharField(max_length=255, null=True)),
                ('supplier_telephone', models.CharField(max_length=255, null=True)),
                ('supplier_email', models.EmailField(max_length=255, null=True)),
                ('supplier_pin_number', models.CharField(max_length=255, null=True)),
                ('supplier_vat_number', models.CharField(max_length=255, null=True)),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='VatCodesListing',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('vat_codes_listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('vat_code', models.CharField(blank=True, max_length=1)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
    ]
