# Generated by Django 3.1.5 on 2021-08-13 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20210812_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsregisterlisting',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.assetsgroupinglisting'),
        ),
    ]
