# Generated by Django 3.1.5 on 2021-08-13 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20210813_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledgerlisting',
            name='sub_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.accountsgroupinglisting'),
        ),
        migrations.AlterField(
            model_name='tenantcustomer',
            name='customer_email',
            field=models.EmailField(blank=True, default='example@email.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='tenantcustomer',
            name='customer_pin_number',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='tenantcustomer',
            name='customer_postal_code',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='tenantcustomer',
            name='customer_telephone',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='tenantcustomer',
            name='customer_vat_number',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='tenantsupplier',
            name='supplier_email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tenantsupplier',
            name='supplier_pin_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tenantsupplier',
            name='supplier_postal_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tenantsupplier',
            name='supplier_telephone',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tenantsupplier',
            name='supplier_vat_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
