# Generated by Django 3.1.5 on 2021-08-20 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_auto_20210812_1200'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0006_bankaccounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierTransaction',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('customer_transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_no', models.CharField(max_length=128, unique=True)),
                ('transaction_type', models.CharField(choices=[('INVOICE', 'INVOICE'), ('CR/TR', 'CR/TR')], default='INVOICE', max_length=128)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('narration', models.CharField(max_length=255)),
                ('posted_date', models.DateField(auto_now=True)),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.bankaccounts')),
                ('posted_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.tenantsupplier')),
                ('vat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.vatcodeslisting')),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='ReceivePayment',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('received_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_no', models.CharField(max_length=128, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('narration', models.CharField(max_length=255)),
                ('posted_date', models.DateField(auto_now=True)),
                ('paid_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.bankaccounts')),
                ('posted_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('received_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.tenantcustomer')),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='MakePayment',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('make_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_no', models.CharField(max_length=128, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('narration', models.CharField(max_length=255)),
                ('posted_date', models.DateField(auto_now=True)),
                ('paid_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.bankaccounts')),
                ('posted_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.tenantsupplier')),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('tenantcustomer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='accounting.tenantcustomer')),
                ('journal_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_no', models.CharField(max_length=128, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('narration', models.CharField(max_length=255)),
                ('posted_date', models.DateField(auto_now=True)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounting.tenantcustomer')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounting.tenantcustomer')),
                ('posted_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('accounting.tenantcustomer',),
        ),
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('customer_transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_no', models.CharField(max_length=128, unique=True)),
                ('transaction_type', models.CharField(choices=[('INVOICE', 'INVOICE'), ('CR/TR', 'CR/TR')], default='INVOICE', max_length=128)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('narration', models.CharField(max_length=255)),
                ('posted_date', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.tenantcustomer')),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.bankaccounts')),
                ('posted_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.vatcodeslisting')),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
    ]
