# Generated by Django 4.0.4 on 2022-04-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_customertransaction_journalentry_makepayment_receivepayment_suppliertransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatcodeslisting',
            name='vat_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
