# Generated by Django 3.1.5 on 2021-08-16 09:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0005_auto_20210814_1217'),
        ('tenant', '0002_auto_20210812_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportInfo',
            fields=[
                ('tenantawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tenant.tenantawaremodel')),
                ('transport_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('inter_field_movement', models.IntegerField()),
                ('target_tons', models.DecimalField(decimal_places=2, max_digits=20)),
                ('actual_tons', models.DecimalField(decimal_places=2, max_digits=20)),
                ('day_condition', models.CharField(choices=[('DRY', 'DRY'), ('WET', 'WET'), ('VERY WET', 'VERY WET')], default='DRY', max_length=255)),
                ('day_direction', models.CharField(choices=[('NORTH', 'NORTH'), ('SOUTH', 'SOUTH'), ('WEST', 'WEST'), ('EAST', 'EAST')], default='NORTH', max_length=255)),
                ('day_status', models.CharField(choices=[('NORMAL', 'NORMAL'), ('HOLIDAY', 'HOLIDAY'), ('PPM', 'PPM'), ('OOC', 'OOC')], default='NORMAL', max_length=255)),
                ('field_clerk_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hr.employee')),
                ('field_clerk_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hr.employee')),
                ('weighbridge_clerk_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hr.employee')),
                ('weighbridge_clerk_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hr.employee')),
            ],
            bases=('tenant.tenantawaremodel',),
        ),
    ]
