# Generated by Django 3.1.5 on 2021-08-16 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportinfo',
            old_name='date',
            new_name='transport_date',
        ),
        migrations.AddField(
            model_name='transportinfo',
            name='posted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transportinfo',
            name='posted_date',
            field=models.DateField(auto_now=True),
        ),
    ]
