# Generated by Django 3.1.5 on 2021-08-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_auto_20210818_0348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packedcane',
            old_name='Tractor',
            new_name='tractor',
        ),
    ]
