# Generated by Django 3.2.6 on 2021-09-06 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_auto_20210820_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivinglicencevalidity',
            name='active_driving_license',
        ),
        migrations.AddField(
            model_name='drivinglicencevalidity',
            name='active_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='drivinglicencevalidity',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='drivinglicencevalidity',
            name='licence_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='field_net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
